// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Func

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> texBuffer;

[numthreads(8, 8, 1)]
void Func(uint3 id : SV_DispatchThreadID)
{
	float w, h;
	texBuffer.GetDimensions(w, h);
	texBuffer[id.xy] = float4(
		id.x / w,
		id.x / w,
		id.x / w,
		(float)1
		);
}
